name: Update Stability AI News

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser pytz

      - name: Run news scraper
        run: python scripts/scrape_rss_news.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "📰 Auto update Stability AI news" || echo "No changes"
          git pull --rebase origin main || echo "No changes to pull"
          git push origin main || echo "Nothing to push"
