name: Update Getty Images Stability AI News

on:
  schedule:
    - cron: '0 * * * *'    # Every hour
  workflow_dispatch:        # Allows manual trigger from Actions tab

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser pytz

      - name: Run news scraper script
        run: python scripts/scrape_rss_news.py

      - name: Commit and push README update
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "📥 Update Getty Images Stability AI news" || echo "No changes to commit"
          git pull --rebase origin main || echo "No changes to pull"
          git push origin main || echo "Nothing to push"
